/**
   \file 
   \brief Constants for bisicles_set_2d_data and bisicles_get_2d_data
 */

#define BISICLES_FIELD_SURFACE_FLUX 1
#define BISICLES_FIELD_BASAL_FLUX 2
#define BISICLES_FIELD_SURFACE_ELEVATION 3
#define BISICLES_FIELD_BEDROCK_ELEVATION 4
#define BISICLES_FIELD_ICE_THICKNESS 5
#define BISICLES_FIELD_THICKNESS 5
#define BISICLES_FIELD_FLOATING_ICE_BASAL_FLUX 6
#define BISICLES_FIELD_GROUNDED_ICE_BASAL_FLUX 7
#define BISICLES_FIELD_OPEN_SEA_BASAL_FLUX 8
#define BISICLES_FIELD_OPEN_LAND_BASAL_FLUX 9
#define BISICLES_FIELD_TEMPERATURE 10
#define BISICLES_FIELD_SURFACE_TEMPERATURE 11
#define BISICLES_FIELD_BASAL_TEMPERATURE 12
#define BISICLES_FIELD_SURFACE_HEAT_FLUX 13
#define BISICLES_FIELD_BASAL_HEAT_FLUX 14
#define BISICLES_FIELD_MELANGE_THICKNESS 15
#define BISICLES_FIELD_TOPOGRAPHY_FLUX 16
#define BISICLES_FIELD_ICE_THICKNESS_HARMONIC 17
