#!/usr/bin/perl
print("plots for 1024 harmonic JFNK \n");
system("scripts/jfnk.awk < run.stream.1024.JFNK.ns4.safety1.harmonic | tee convergence/twistyStream/doc/solverPerformance/outer.jfnk.harmonic.1024");
system("scripts/innerJFNK.awk < run.stream.1024.JFNK.ns4.safety1.harmonic | tee convergence/twistyStream/doc/solverPerformance/inner.jfnk.harmonic.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.jfnk.harmonic.1024.temp convergence/twistyStream/doc/solverPerformance/inner.jfnk.harmonic.1024");
print("plots for 1024 arith JFNK \n");
system("scripts/jfnk.awk < run.stream.1024.JFNK.ns4.safety1.arithmetic | tee convergence/twistyStream/doc/solverPerformance/outer.jfnk.arith.1024");
system("scripts/innerJFNK.awk < run.stream.1024.JFNK.ns4.safety1.arithmetic | tee convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.1024.temp convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.1024");
print("plots for 1024 arith JFNK 2V-cycle \n");
system("scripts/jfnk.awk < run.stream.1024.JFNK.ns4.safety1.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/outer.jfnk.arith.2V.1024");
system("scripts/innerJFNK.awk < run.stream.1024.JFNK.ns4.safety1.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.1024.temp convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.1024");
print("plots for 1024 arith JFNK 2V-cycle, 8smooth \n");
system("scripts/jfnk.awk < run.stream.1024.JFNK.ns8.safety1.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/outer.jfnk.arith.2V.ns8.1024");
system("scripts/innerJFNK.awk < run.stream.1024.JFNK.ns8.safety1.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns8.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns8.1024.temp convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns8.1024");
print("plots for 1024 arith JFNK 2V-cycle, 8smooth, safety0.75 \n");
system("scripts/jfnk.awk < run.stream.1024.JFNK.ns8.safety0.75.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/outer.jfnk.arith.2V.ns8.safety0.75.1024");
system("scripts/innerJFNK.awk < run.stream.1024.JFNK.ns8.safety0.75.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns8.safety0.75.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns8.safety0.75.1024.temp convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns8.safety0.75.1024");
print("plots for 1024 arith JFNK 2V-cycle, 4smooth, safety0.75 \n");
system("scripts/jfnk.awk < run.stream.1024.JFNK.ns4.safety0.75.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/outer.jfnk.arith.2V.ns4.safety0.75.1024");
system("scripts/innerJFNK.awk < run.stream.1024.JFNK.ns4.safety0.75.arithmetic.2Vcycle | tee convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns4.safety0.75.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns4.safety0.75.1024.temp convergence/twistyStream/doc/solverPerformance/inner.jfnk.arith.2V.ns4.safety0.75.1024");
print("plots for 1024 arith Picard 2V-cycle, 4smooth, safety1.0 \n");
system("scripts/picard.awk < run.stream.1024.picard.ns4.safety1.0.arithmetic.mg | tee convergence/twistyStream/doc/solverPerformance/outer.picard.arith.mg.ns4.safety1.0.1024");
system("scripts/innerPicard.awk < run.stream.1024.picard.ns4.safety1.0.arithmetic.mg | tee convergence/twistyStream/doc/solverPerformance/inner.picard.arith.mg.ns4.safety1.0.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.picard.arith.mg.ns4.safety1.0.1024.temp convergence/twistyStream/doc/solverPerformance/inner.picard.arith.mg.ns4.safety1.0.1024");
print("plots for 1024 harmonic Picard 2V-cycle, 4smooth, safety1.0 \n");
system("scripts/picard.awk < run.stream.1024.picard.ns4.safety1.0.harmonic.mg | tee convergence/twistyStream/doc/solverPerformance/outer.picard.harmonic.mg.ns4.safety1.0.1024");
system("scripts/innerPicard.awk < run.stream.1024.picard.ns4.safety1.0.harmonic.mg | tee convergence/twistyStream/doc/solverPerformance/inner.picard.harmonic.mg.ns4.safety1.0.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.picard.harmonic.mg.ns4.safety1.0.1024.temp convergence/twistyStream/doc/solverPerformance/inner.picard.harmonic.mg.ns4.safety1.0.1024");
print("plots for 1024 arith Picard 2V-cycle, 8smooth, safety0.75 \n");
system("scripts/picard.awk < run.stream.1024.picard.ns4.safety0.75.arithmetic.mg | tee convergence/twistyStream/doc/solverPerformance/outer.picard.arith.mg.ns4.safety0.75.1024");
system("scripts/innerPicard.awk < run.stream.1024.picard.ns4.safety0.75.arithmetic.mg | tee convergence/twistyStream/doc/solverPerformance/inner.picard.arith.mg.ns4.safety0.75.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.picard.arith.mg.ns4.safety0.75.1024.temp convergence/twistyStream/doc/solverPerformance/inner.picard.arith.mg.ns4.safety0.75.1024");
print("plots for 1024 arith Picard 1V-cycle, 4smooth, safety1.0 BiCG \n");
system("scripts/picard.awk < run.stream.1024.picard.ns4.safety1.0.arithmetic.biCG | tee convergence/twistyStream/doc/solverPerformance/outer.picard.arith.biCG.ns4.safety1.0.1024");
system("scripts/innerPicard.awk < run.stream.1024.picard.ns4.safety1.0.arithmetic.biCG | tee convergence/twistyStream/doc/solverPerformance/inner.picard.arith.biCG.ns4.safety1.0.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.picard.arith.biCG.ns4.safety1.0.1024.temp convergence/twistyStream/doc/solverPerformance/inner.picard.arith.biCG.ns4.safety1.0.1024");
print("plots for 1024 arith Picard 2V-cycle, 4smooth, safety1.0 BiCG \n");
system("scripts/picard.awk < run.stream.1024.picard.ns4.safety1.0.arithmetic.2V.biCG | tee convergence/twistyStream/doc/solverPerformance/outer.picard.arith.2V.biCG.ns4.safety1.0.1024");
system("scripts/innerPicard.awk < run.stream.1024.picard.ns4.safety1.0.arithmetic.2V.biCG | tee convergence/twistyStream/doc/solverPerformance/inner.picard.arith.2V.biCG.ns4.safety1.0.1024.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.picard.arith.2V.biCG.ns4.safety1.0.1024.temp convergence/twistyStream/doc/solverPerformance/inner.picard.arith.2V.biCG.ns4.safety1.0.1024");
print("plots for smallerL1L2 tolerance \n");
system("scripts/picard.awk < run.smallerL1L2Tol | tee convergence/twistyStream/doc/solverPerformance/outer.smallerL1L2Tol");
system("scripts/innerPicard.awk < run.smallerL1L2Tol | tee convergence/twistyStream/doc/solverPerformance/inner.smallerL1L2Tol.temp");
system("scripts/a.out convergence/twistyStream/doc/solverPerformance/inner.smallerL1L2Tol.temp convergence/twistyStream/doc/solverPerformance/inner.smallerL1L2Tol");




