#!/usr/bin/python
from argparse import *
import os
import glob
import platform
from datetime import date

today = date.today()

print("Today's date:", today)

parser = ArgumentParser()

parser.add_argument('--min_num_cells', type=int, help='Smallest problem domain size to set up [64].'  ,default='64')
parser.add_argument('--max_num_cells', type=int, help='Largest  problem domain size to set up [64].'  ,default='64')
parser.add_argument('--input_template_dir', type=str, help='Directory of input file templates [../_input_templates].' ,default="../_input_templates")
parser.add_argument('--batch', type=str, help='batch file template'   ,default="_batch_templates/serial.batch")
parser.add_argument('--prefix', type=str, help='name of test["_prch_compare"]',default="prch_compare")

args = parser.parse_args()
print(args)
homestr = os.getcwd();
print ("homedir = " + homestr)
neartop_directory = homestr + "/_" +args.prefix
strtoday =str(today.month) + "_" + str(today.day) + "_" + str(today.year)
top_directory = neartop_directory + "_" + strtoday
print ("top_directory = " + top_directory)
if not os.path.exists(top_directory):
    printstr = "making directory " + top_directory
    print (printstr)
    os.mkdir(top_directory)
    
i_min_case = 0
i_max_case = 1

operators=["helmholtz"
           "conductivity"
           "viscous_tensor"
           "resistivity"]

# loop through cases to run
i_case = i_min_case
while i_case <= i_max_case:
    i_dim = 2
    # loop through dimensions
    while i_dim <= 3:
        #loop through opt     
        i_opt = 0
        while i_opt <= 1:
            #I hesitate to use = when directories will be made
            #This also allows the directory name to be less shouty
            opt_status = "opt_false"
            opt_gmake  = "OPT=FALSE"
            deb_status = "debug_true"
            deb_gmake  = "DEBUG=TRUE"
            
            if(i_opt == 1):
                opt_status = "opt_high"
                opt_gmake  = "OPT=HIGH"
                deb_status = "debug_false"
                deb_gmake  = "DEBUG=FALSE"

            i_ncells = args.min_num_cells
            while i_ncells <=  args.max_num_cells:
                str_config = "_case_" + str(i_case) + "_" + str(i_dim) + "_" + opt_status + "_" + deb_status + "_nx_" + str(i_ncells)
                printstr = "configuration string = " + str_config
                print (printstr)
                config_directory = top_directory + "/" + str_config
                printstr =  "configuration directory = " + config_directory
                print(printstr)
                if not os.path.exists(config_directory):
                    printstr = "making directory " + config_directory
                    print (printstr)
                    os.mkdir(config_directory)

                i_opera = 0
                while i_opera <= 3:
                    op_str = "4586"
                    if(i_opera == 0):
                        op_str = "helmholtz"
                    if(i_opera == 1):
                        op_str = "conductivity"
                    if(i_opera == 2):
                        op_str = "viscous_tensor"
                    if(i_opera == 3):
                        op_str = "resistivity"

                    old_directory = config_directory + "/_old_" + op_str
                    amr_directory = config_directory +  "/amr_" + op_str
                    printstr = "old_directory = " + old_directory
                    print (printstr)
                    printstr = "amr directory =  " + amr_directory
                    print (printstr)
                    if not os.path.exists(old_directory):
                        os.mkdir(old_directory)
                    if not os.path.exists(amr_directory):
                        os.mkdir(amr_directory)
                    # here goes nothing
                    exec_directory_old = homestr + "/../../_old_" + op_str
                    printstr = "exec_directory_old = " + exec_directory_old
                    print(printstr)
                    exec_directory_amr = homestr + "/../../amr_" + op_str
                    printstr = "exec_directory_amr = " + exec_directory_amr
                    input_name = "case_" + str(i_case) + ".inputs"
                    print(printstr)
                    command_old = "cd " + exec_directory_old + "; make main; mv main.exe " + old_directory + "; cp _inputs/" + input_name + " " + old_directory
                    command_amr = "cd " + exec_directory_old + "; make main; mv main.exe " + amr_directory + "; cp _inputs/" + input_name + " " + amr_directory
                    printstr = "command_old = " + command_old
                    print(printstr)
                    os.system(command_old)
                    printstr = "command_amr = " + command_amr
                    print(printstr)
                    os.system(command_amr)
                    i_opera = i_opera + 1
                    # end loop over operators
                    
                    
                i_ncells = 2*i_ncells
                # end loop over values of nx
                
            i_opt = i_opt + 1
            # end loop over values of i_opt


        i_dim = i_dim + 1
        # end loop over values of i_dim

    i_case = i_case + 1
    # end loop over values of i_case
    
